### ISSUE TITLE
Transition and Trail combination

### ISSUE THREAD

**Issue by mateeyow** [drcmda/react-spring#105]
In a way this issue is related to #86. But what I am trying to do is to animate/change the background color of the list item once the value changes. But somehow, the setInterval does not work. The values of the list somehow doesn't change. Am I missing something? Here is my codesandbox: https://codesandbox.io/s/5zrw9qj00p

P.S. This and css-transition-group is the only animation library that I find very easy to use. Keep it up! I want to contribute though but I don't think my skills is adequate enough.

**Comment by drcmda** [comment]
@mateeyow it's probably this line: https://github.com/drcmda/react-spring/blob/master/src/Keyframes.js#L30

This came after a code-review that Dan Abramov made, but perhaps it's too strict. It won't render the list unless the state changes. This one is tricky, because if we remove that check it would render always since you re-create the render-prop, essentially giving it a new function on each render. But at the same time i can see how that would block your use-case. Perhaps this would be a great way to contribute - play around with it and make a PR once it fits. You can copy the whole file (Keyframes.js) and fetch the imports directly from 'react-spring'.

**Comment by mateeyow** [comment]
Hmm. I'll try. Thing is, if I use a regular `Trail` the data is updated. Am I using `Keyframes` wrong?

**Comment by drcmda** [comment]
No, but Keyframes has shouldComponentUpdate - it currently only reacts to changes to the state prop, which is not enough.

**Comment by mateeyow** [comment]
Hmm. Would it affect the performance if I check the equality of the
children?

**Comment by drcmda** [comment]
Not really, it should be fairly inexpensive. Even if you use non-native springs, it's the content that renders, not the outer primitive.

**Comment by drcmda** [comment]
@mateeyow could you try again, i made an update to how spring and keyframes react to updates ...

**Comment by drcmda** [comment]
@mateeyow transition has a delay prop now that can trail adds/removes. See: http://react-spring.surge.sh/transition#props
