### ISSUE TITLE
SpringAnimation vs OscillatorAnimation

### ISSUE THREAD

**Issue by subhero24** [drcmda/react-spring#108]
Besides SpringAnimation there are also implementations for TimingAnimation and OscillatorAnimation.

What is the practical difference between SpringAnimation and OscillatorAnimation?

**Comment by drcmda** [comment]
@subhero24 the OscillatorAnimation is the exact same spring that IOS and react-native use. It has the additional `mass` property.  The default spring is a RK4 spring (Runge-Kutta of Order 4). This used to be the default in RN and is still the default in animated, i'm using it as default as well because it's a little easier to configure.

**Comment by skevy** [comment]
Hi @drcmda! Just wanted to chime in here as I wrote the new Spring algorithm in iOS/React Native.

You can actually configure the RK4 spring exactly the same way as the close-form DHO spring. You can convert directly between stiffness/damping/mass and tension/friction...and it will work exactly the same as the RK4.

**Comment by drcmda** [comment]
@skevy i did: https://github.com/drcmda/react-spring/commit/ff4af0f0d4676f7e067d034aaf14abd69e2bce0b

but then had to revert as it would behave differently in some situations. Here's an example: https://codesandbox.io/s/53q7oxxpxp

If you uncomment `impl={OscillatorAnimation}` it seems to behaves odd. Do you know what it could be?

Thanks for you incredible work btw!

**Comment by skevy** [comment]
@drcmda here's a start: https://codesandbox.io/s/wwjw9x66zk

There was an actual bug in the oscillatorAnimation -- it wasn't setting the initialVelocity correctly when starting with a previous animation.

You can see now it's at least a lot less janky.

However, while it looks like an actual spring now (lol), it's not the same curve (or at least, it's not the same speed) as the RK4 animation. I didn't dig in too far yet, but it seems like with react-spring you're creating a new instance of the animation per frame and essentially calling `.start` on every frame, is that right?

I tested this pretty heavily when I wrote the initial implementation, but I'd be curious if you put two springs (with the different implementations) side by side and just start the animation, without starting it every frame, if they look the same. They should, and if that's the case, I think the inconsistency has to do with how we're dealing with velocity.

**Comment by drcmda** [comment]
@skevy back from vacation :-) looks way better now. it shouldn't call start on every frame, the raf updater calls the updating functions and from there on it goes into the dom (or re-rerendered as props). every outside render pass (where values change) calls .start otherwise.

Should i update the new oscillator you made for now?

**Comment by dariocravero** [comment]
On this topic @drcmda, React Native's implementation of Spring supports [a few other combinations of parameters like speed and bounciness](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/animations/SpringAnimation.js#L101-L144). Were they intentionally left out of react-spring's implementation? Would you consider bringing them back? Thanks!

**Comment by drcmda** [comment]
@dariocravero isn't speed and bounciness the same as tension & friction, or stiffness & damping? I did initially remove it for the sake of making it easier to configure.

**Comment by dariocravero** [comment]
@drcmda you're right. Eventually, yes, React Native maps them down to stiffness, damping and mass at some point. However, their semantics are somewhat different and, at least in our case, the designers we've been working with found `bounciness` and `speed` more intuitive than `friction` and `tension`.

**Comment by drcmda** [comment]
@dariocravero it would kind of be a pain to explain this or type this out in TS. https://github.com/drcmda/react-spring/blob/master/API.md#spring-configs

What would be awesome though, you could take your gist and make a repo for it, publish it on npm. I broke animated into pieces so that it's fully modular, there could actually be an eco system now of different springs, interpolators, and so on. Your team could then use bounciness and speed.

**Comment by dariocravero** [comment]
Yeah, thanks for the suggestion, I already did that here https://github.com/viewstools/animations :) -it needs some cleanup to only integrate the bits it uses but it's a start.
