### ISSUE TITLE
Removing styles after enter transition

### ISSUE THREAD

**Issue by jamiewinder** [drcmda/react-spring#173]
I'm new to this library, and have a scenario which I'm struggling to model and a proposed solution unless anyone can point me toward something which I can use now.

I'm using `Transition` to animate the appearance of some items in a list. Amongst other properties, I'm animating `opacity` from `0` to `0.9` for enter, and from `0.9` to `0` for leave. I also want to add a hover effect to this so that I can set the opacity to `1`. 

I have set up a CSS `:hover` rule for this but since react-spring applies the opacity values to `style`, I can't apply it (without using !important). Is there a way that I can ask react-spring to remove its `style` values when not in transition? I'd see this as an intermediate state between the `enter` and `leave` states, something like:
```jsx
enter={{ opacity: 0.9 }}
entered={{}}
leave={{ opacity: 0 }}
```
`entered` = the styles values to apply immediately after the `enter` transition - in this case nothing (I can use a class to retain the opacity value if I so choose, and use normal CSS to get the hover effect I want).

**Comment by drcmda** [comment]
Well, there's `update`, which is called for everything that is't from/enter/leave (basically it meas other items came in or went out). You could also try onRest. But generally mixing css animation with js-animation isn't going to work out well. A spring has a precision that takes some time to complete, so it will also ehave jumpy even if you manage to remove styles. If you want to take precedence then this is what !important is there for. 

Otherwise, do the hover with react-spring, you can re-use your transition for this and use the updated props. I just did exactly that for a lib: https://github.com/drcmda/mauerwerk That's one transition and it tracks exit/leave as well as animating zoom in and out.
