### ISSUE TITLE
Weird bug that causes loads of white space below content

### ISSUE THREAD

**Issue by A7DC** [drcmda/react-spring#217]
Totally lost here... I'm struggling to get animations (based on scroll position) to play well with the animations on route changes. 

When you scroll really fast on the homepage, it has all this white space underneath the content, like so:

![untitled](https://user-images.githubusercontent.com/3710703/44939240-c89b6080-add7-11e8-90c7-50b88c6f57c1.gif)

I can prevent this by using `overflow: scroll` on the `Home` components container, but then `window.scrollY` will always return 0 so none of the scrolling animations work.

Has anyone got any project examples of where they've animated routes, and then also animated elements based off their scroll position? Would be a huge help!

Here's [a Codesandbox](https://codesandbox.io/s/kk430359mr) demonstrating the issue.

Thanks!

**Comment by drcmda** [comment]
That's hard to track due to the complexity of the sandbox, and most likely an issue with the code handling the scroll positions. The parallax primitive uses scrollposition: https://codesandbox.io/embed/548lqnmk6l but it uses the imperate api (import { AnimatedValue } from 'react-spring').

If you could isolate a little more i would find it easier to figure out whats going on.

**Comment by drcmda** [comment]
@A7DC first thing, you're using react and react-dom 16.3.x, there was a major bug in there that was later fixed in 16.4.x. If you move up transition behaves correctly.

Though that doesn't (yet) fix your problem. Now it distributes the overflow container correctly but you're still pushing the exit-route 500px lower, which means it will occupy that space until it's gone, it will snap back in other words, which isn't what you want, though this was the bug, in 16.3.x getDerivedStateFromProps won't fire, therefore the route stays and occupies space.
