### ISSUE TITLE
Problem With Transition !!!

### ISSUE THREAD

**Issue by kryptonian41** [drcmda/react-spring#219]
This is what's happening, only the loader fades in and out the other component just get in and out normally. And also distorts the whole layout while the transition.

![ezgif-2-d417a82282](https://user-images.githubusercontent.com/22504055/44960302-c68dea80-af1a-11e8-9247-b4ba4faaf946.gif)

Here is my code for the component: [https://github.com/kryptonian41/sereact/blob/master/src/components/dashboard.js](url)

**Comment by drcmda** [comment]
Doesn't look like you pass on styles:

```jsx
<Transition
              from={{ opacity: 0 }}
              enter={{ opacity: 1 }}
              leave={{ opacity: 0 }}
            >
              {dataLoaded
                ? function(style) {
                    return (
                      <Content style={{ ...style, ...styles.contentContainer }}>
                        dashboard
                      </Content>
                    )
                  }
                : style => <Loader styles={style} />}
            </Transition>
```

**Comment by drcmda** [comment]
> Loader is my own component

Sure, just looked a little off to me. The main reason was probably passing styles.

> Also regarding stacking the components on top of each other.

You can also use a spring, it doesn't have to be a transition. It can even be faster since elements don't have to re-mount when they come in again. I personally do this even for sidebars. Other than that, transition isn't magic, it basically is a lifecycle preserver, the output stack it gives you is raw html, how you treat it or visualize it is up to you.

> And can I ask why you passed dataLoaded as the key prop to the Transition component ?

When you don't specify a key it takes the function itself as a key, the full thing, as a string. It works but it's cleaner when you already have a atomic key.

**Comment by kryptonian41** [comment]
Okay, I got it and thanks for reciprocating so quickly.
