### ISSUE TITLE
Child components of Transitions remounts

### ISSUE THREAD

**Issue by einarlove** [drcmda/react-spring#249]
I've had an issue where Transition remounts my components constantly even when Transition enter/leave is idle.

I'm tried to boil the problem down to the [smallest example](https://codesandbox.io/s/z34l7lnvxl) even tho it does not quite resemble my issue where I have 20 remounts on one component but non the less it remounts when it shouldn't. Check the console and you'll see that the fourth item unmounts as expected, but gets remounted again.

I tried console.log'ing all over `react-spring` codebase and saw that Transition was quiet and so was it's rendering, but the Spring within was remounting.

**Comment by einarlove** [comment]
I tried console.log'ing all over `react-spring` codebase and saw that Transition was quiet and so was it's rendering, but the Spring within was remounting.

**Comment by einarlove** [comment]
I updated react, react-dom and react-spring to latest on CodeSandbox and now it works, so I'll come back with how my example break.

**Comment by einarlove** [comment]
I successfully narrowed it down in a [new CodeSandbox](https://codesandbox.io/s/x73k65q2rw). The sinner seems to be animating `height: 'auto'`.

**Comment by einarlove** [comment]
#250 Fixes most of the issues, but I've encountered other bugs related to `height: auto` not solved.
When doing this:
```jsx
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 'auto' }}
leave={{ opacity: 0 }}
```
or
```jsx
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 'auto' }}
leave={{ opacity: 0, 'auto' }}
```
the component never unmounts.

**Comment by drcmda** [comment]
I noticed the same when trying to fix keyframes, normally springs remember values, but these abstracted primitives seem to have problems dealing with auto as it has to go through multiple async states to properly calculate a value. Surprises me a little since Transition does spread current values before new values to ensure it acts additively: https://github.com/drcmda/react-spring/blob/master/src/Transition.js#L157

**Comment by einarlove** [comment]
Also had a big proben where my Keyframes within the Transition stopped at random positions everytime and never completed.

**Comment by einarlove** [comment]
And some problems where height:auto calculated to infinity on leave. The bugs might not be related tho.

**Comment by drcmda** [comment]
Thanks for the PRs btw, really appreciate it! I'm on it otherwise.

**Comment by drcmda** [comment]
@einarlove Issues should be fixed in 5.9.2, this works now:

```jsx
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 'auto' }}
leave={{ opacity: 0 }}
```

Of course it'll simply remove the component when it's done since it doesn't shrink that way. Btw, make sead sure you're on React 16.4.x or higher, 16.3.x had a buggy getDerivedStateFromProps implementation (it didn't fire after setState).

This:

```jsx
from={{ opacity: 0, height: 0 }}
enter={{ opacity: 1, height: 'auto' }}
leave={{ opacity: 0,  'auto' }}
```

isn't valid javascript, you probably meant something else?

**Comment by drcmda** [comment]
I've made some steps forward tinkering with array props for transition, this is now wrapping reacts transitiongroup: https://codesandbox.io/s/lr1lrw9mkm

If i can get the same functionality out of this perhaps it would make sense to replace the current implementation. This would also take a major burden off my shoulders not having to manager component states.

**Comment by einarlove** [comment]
_We got our discussion scattered across [twitter](https://twitter.com/einarlove/status/1047558699420672000), [pull request](https://github.com/drcmda/react-spring/pull/250) and this issue, but I think we should stick with one of them 😅. I suggest here._

I finally got around making a demo explaining the issues I've mentioned before with buggy `height:auto` calculations and `<Keyframes>` acting weird when inside the `<Transition>`.

**https://codesandbox.io/s/538pp24yyk**

It might seem overcomplicating things, but I tried my best to make the example resemble how it works in my application.

There are 3 problems displayed in the example.
1. When the <Message> gets mounted in the list and gets height animated from 0 → auto, it doubles the height. It only happens to the first element making me believe it's because the parent has no set height/width on first pain(?). Somehow I fixed this in my app by setting explicit `width: 500px;` and letting children be auto width. It's a hack, not a permanent solution.
1. I do not know how to describe it, but look at the messages when they are unmounted and are supposed to fade out and animate height to 0. It's a mess. They are jumping upwards and switching positions.
1. The keyframes within the <Message> does not animate correctly. It staggers and does not complete by the desired duration spesified. If you move it outside <Transition> it works. Make it a <Spring>, it works.

**Comment by drcmda** [comment]
@einarlove Transition can now officially handle arrays/chains: https://twitter.com/0xca0a/status/1049353646868193280

So i think your example would be easier to implement. Let me give it a shot tomorrow. I'm certain i can cook this down to nothing with the 6.x branch.

As for width, the way it works is that it takes the element out of its context and gives it position absolute. If the parent element isn't relative or absolute, it takes the parents parent, and so on, this is how css works. More on that here: http://react-spring.surge.sh/gotchas (animating auto).

And as for Keyframes, it had a bug where you couldn't really use onRest because it wouldn't wait until finish. Now that 6.x transition uses keyframes i stumbled over this and fixed it. Here is an easy staggered example: https://codesandbox.io/embed/pm9332mkmx As you see, it runs the full animation on unmount.

**Comment by drcmda** [comment]
@einarlove I think i have it down: https://codesandbox.io/embed/kp527wn3r
