### ISSUE TITLE
question: routing Transition in v6

### ISSUE THREAD

**Issue by renrizzolo** [drcmda/react-spring#291]
Hi, I'm having trouble updating a `react-router` routing transition for v6.

5.9.2: https://codesandbox.io/s/k559o99wjo
6.1.4: https://codesandbox.io/s/5k4z32ynnl

The difference/problem being that in the v6 version the new route shows immediately, then the styles are applied (i.e the old route is replaced by the new route, then the new route instantly leaves then enters). I've tried passing the routes to `items` but it didn't help.

Is this way of implementing route transitions no longer compatible?

Sorry if this has been covered but I couldn't find a solution.

**Comment by drcmda** [comment]
Fixed example: https://codesandbox.io/s/ko0v5l9303

```jsx
                <Transition
                  items={location}
                  keys={location => location.pathname}
                  from={{opacity: 0, transform: 'translateY(100px)'}}
                  enter={{opacity: 1, transform: 'translateY(0)'}}
                  leave={{opacity: 0, transform: 'translateY(50px)'}}>
                  {location => style => (
                      <Switch location={location}>
```

In 6 you always pass items and if necessary use keys to teach it how to extract item-keys. You don't map through stuff any longer in the function child, instead you get the individual item (in your case the location) and return a function-component. You should always rely on the item that comes out below, because you could be rendering something that has already been deleted or changes - which is the case here, since routes change and you render the current or updated state, not the retained state, which doesn't exist in react-router any longer, but is retained inside transition.

More about that here: http://react-spring.surge.sh/transition

**Comment by renrizzolo** [comment]
@drcmda you're a champion. Thanks for clearing it up!
