### ISSUE TITLE
Transition delay after animation is done

### ISSUE THREAD

**Issue by alexluong** [drcmda/react-spring#99]
Hi,

I'm quite new to React Spring. I noticed that there is a slight transition delay after the animation is done. Here is the codesandbox that can show you that: https://codesandbox.io/s/91362333po

I just added `config={config.slow}` to emphasize the delay and added a `console.log` on `onRest`. If you click to make the transition, you can see that after the animation is done, it took an extra 300ms - 500ms until onRest is fired.

I don't know if this is a design choice? If I don't want to have this behavior, how can I go around it?

Thank you so much.

**Comment by drcmda** [comment]
this is just the springs precision, you can play around with some of the hidden config values to make it more swift:

```jsx
config={{
  ...config.default,
  restSpeedThreshold: 1,
  restDisplacementThreshold: 0.01,
  overshootClamping: true,
}}
```

Generally relying on onRest isn't the best idea since springs are supposed to be fluid, but if you have to, then precision comes in handy, or you switch to a time based implementation + easing:

https://github.com/drcmda/react-spring#timeduration-based-implementations-and-addons-demo

**Comment by alexluong** [comment]
@drcmda Thank you very much for the super prompt reply. That helps a lot. Time-based implementation and easing do it for me.

May I ask what are the pros and cons of time-based implementation and normal react-spring animation? I wonder if people can use time-based impl to achieve precision, why would they choose to go with the normal animation then?

**Comment by drcmda** [comment]
Personally i am over it. This explains it pretty well: https://www.youtube.com/watch?v=1tavDv5hXpo&feature=youtu.be&t=6m3s

With springs you just animate, the spring will worry about dynamics, rest-time, additive chaining and so on. The state and place where it's at doesn't matter so much, it will additively animate between one state to another - which makes it perfect for fluid, physically accurate UI animations.

Duration based animations are opposed to that. They are not based on physics but time. If moving between A to B takes 2 sec, but due to user interaction the movable object is already half-way through, if you start the animation from here it will still take 2 seconds. Another thing that's really hard to get right is easings and correct timings - you know this from css, 0.5s here, 1s there, in, out, cubic, whatever - and in the end it looks like a mess.

**Comment by alexluong** [comment]
That makes sense. The component I was animating only has 2 states and relies on animationEnd callback, so I didn’t have to worry about chaining and so on. Therefore, duration based worked better for me. However, I do see the advantages of the other aproach.

Thanks for the replies. They are very helpful. I’m loving the library so far.

**Comment by drcmda** [comment]
For sure, there are indeed situations where duration makes total sense. I guess i can close this down.
